# language: python
checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    excluded_paths:
        - "tests/"
build:
    environment:
        python: 3.5.1
        mysql: false
        postgresql: false
        mongodb: false
        elasticsearch: false
        redis: false
        memcached: false
        neo4j: false
        rabbitmq: false
        docker:
            remote_engine: true
    tests:
        before:
            - "virtualenv -p /usr/bin/python3 venv"
            - "source venv/bin/activate"
            - "pip install ."
            - "stakkr-init"
            - "pip install -r requirements-dev.txt"
        override:
            -
                command: "py.test --cov-report html --cov-report term --cov=stakkr tests/"
                coverage:
                    file: '.coverage'
                    format: 'py-cc'
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    - py-scrutinizer-run
                    -
                        command: pylint-run
                        use_website_config: true
