sudo: required
dist: trusty

language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - pip install .
    - stakkr-init
    - pip install -r requirements-dev.txt

# command to run tests
script: py.test --cov-report html --cov-report term --cov=stakkr tests/
