---

environment: dev

services:
  adminer:
    enabled: false
    version: latest
    ram: 256M

  apache:
    enabled: false
    version: latest
    ram: 512M

  elasticsearch:
    enabled: false
    version: latest
    ram: 2048M

  kibana:
    enabled: false
    version: latest
    ram: 2048M

  logstash:
    enabled: false
    version: latest
    ram: 2048M

  mailcatcher:
    enabled: false
    version: latest
    ram: 256M

  maildev:
    enabled: false
    version: latest
    ram: 256M

  mongo:
    enabled: false
    version: latest
    ram: 1024M

  mysql:
    enabled: false
    version: latest
    ram: 1024M
    root_password: root

  nginx:
    enabled: false
    version: latest
    ram: 1024M
    document_root: /var/www

  php:
    enabled: false
    version: latest
    ram: 1024M

  phpmyadmin:
    enabled: false
    version: latest
    ram: 256M
    upload_max_filesize: 256M

  portainer:
    enabled: false
    version: latest
    ram: 512M

  postgres:
    enabled: false
    version: latest
    ram: 1024M
    password: postgres

  sqlserver:
    enabled: false
    version: latest
    ram: 1024M
    password: postgres

  redis:
    enabled: false
    version: latest
    ram: 1024M

  xhgui:
    enabled: false
    version: latest
    ram: 1024M

proxy:
  enabled: true
  domain: localhost
  port: 80

project_name: ''

network-block:
  php: [25, 465, 587]

subnet: ''

uid: 1000
gid: 1000