version: '2.2'

services:
    mailcatcher:
        image: tophfr/mailcatcher
        container_name: ${COMPOSE_PROJECT_NAME}_mailcatcher
        hostname: ${COMPOSE_PROJECT_NAME}_mailcatcher
        networks: [stakkr]
        labels:
          - traefik.frontend.rule=Host:mailcatcher.${COMPOSE_PROJECT_NAME}.${PROXY_DOMAIN}
